spring:
  security:
    oauth2:
      client:
        registration:
          #          google:
          #            client-id: 1062753642703-6q4evbgpco0et7t6s7u468b7vj04hi6q.apps.googleusercontent.com
          #            client-secret: # 입력
          #            scope: profile,email
          kakao:
            client-id: # 입력
            client-name: Kakao
            redirect-uri: "http://54.180.12.194:8080/login/oauth2/code/kakao"
            scope: profile_nickname, profile_image, account_email
            authorization-grant-type: authorization_code
            client-authentication-method: POST
          naver:
            client-id: # 입력
            client-secret: # 입력
            redirect-uri: "http://54.180.12.194:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
